server:
  port: ${PORT:8761}
  
spring:
  application:
    name: service-discovery
    
eureka:
  instance:
    hostname: ${HOSTNAME:localhost}
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://${HOSTNAME:localhost}/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"
 
