server:
  port: ${PORT:9002}

spring:
  application:
    name: service-scheduler
  jpa: 
    properties:
      hibernate:
        formatSql: true
        jdbc:
          lob:
            non-contextual-creation: true
    databasePlatform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: false 
    hibernate: 
      ddlAuto: update 
      naming:
        implicitStrategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
  datasource: 
    url: jdbc:mysql://localhost:3306/ibwise 
    username: root 
    password: rootroot 
    driverClassName: com.mysql.jdbc.Driver
 
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://localhost:8761}/eureka
 
 
